# Generated by Django 4.0.3 on 2022-03-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
